Repository QuantEcon/QuantEcon.py, pull requests merged in 2018-06, with the labels that each got.

#409 add minimum version number for numba support
  setup.py
Labels: in-work

#412 TEST: Fix test_discrete_rv
  quantecon/tests/test_discrete_rv.py
Labels: ready, refactor, tests

#415 Add `'interior-point'` option to `is_dominated`; add `dominated_actions`
  quantecon/game_theory/normal_form_game.py
  quantecon/game_theory/tests/test_normal_form_game.py
  setup.py
Labels: enhancement, ready
