Repository QuantEcon/QuantEcon.py, pull requests merged in 2018-10, with the labels that each got.

#437 Add method option in robustlq.py
  quantecon/robustlq.py
  quantecon/tests/test_robustlq.py
Labels: enhancement, ready

#436 Remove `from future import ...`
  quantecon/estspec.py
  quantecon/ivp.py
  quantecon/lqnash.py
  quantecon/markov/core.py
  quantecon/markov/ddp.py
  quantecon/markov/tests/test_core.py
  quantecon/markov/tests/test_ddp.py
  quantecon/markov/tests/test_gth_solve.py
  quantecon/matrix_eqn.py
  quantecon/quad.py
  quantecon/robustlq.py
  quantecon/tests/test_compute_fp.py
  quantecon/tests/test_ecdf.py
  quantecon/tests/test_estspec.py
  quantecon/tests/test_lae.py
  quantecon/tests/test_lqnash.py
  quantecon/tests/test_matrix_eqn.py
  quantecon/tests/test_quad.py
Labels: ready, refactor

#439 Fix issue#367
  quantecon/kalman.py
  quantecon/tests/test_kalman.py
Labels: enhancement, ready

#438 Fix docstring of x_hat in Kalman class
  quantecon/kalman.py
Labels: ready

#430 Add LGTM code quality badges
  README.md
Labels: ready

#414 Added basic inequality mesasures: lorenz curve and gini
  quantecon/__init__.py
  quantecon/inequality.py
  quantecon/tests/test_inequality.py
Labels: ready
