Repository QuantEcon/QuantEcon.py, pull requests merged in 2018-11, with the labels that each got.

#443 FIX: Disallow Player with 0 actions
  quantecon/game_theory/normal_form_game.py
  quantecon/game_theory/tests/test_normal_form_game.py
Labels: ready

#444 Add Player.delete_action, NormalFormGame.delete_action
  quantecon/game_theory/normal_form_game.py
  quantecon/game_theory/tests/test_normal_form_game.py
Labels: enhancement, ready

#441 FEAT: Add the Nelder-Mead algorithm
  quantecon/optimize/__init__.py
  quantecon/optimize/nelder_mead.py
  quantecon/optimize/tests/__init__.py
  quantecon/optimize/tests/test_nelder_mead.py
Labels: ready

#433 ENH: Add AS algorithm.
  quantecon/game_theory/__init__.py
  quantecon/game_theory/repeated_game.py
  quantecon/game_theory/tests/test_repeated_game.py
Labels: enhancement, in-work
