Repository QuantEcon/QuantEcon.py, pull requests merged in 2021-05, with the labels that each got.

#581 MAINT: Use multivariate_normal via random_state
  quantecon/lss.py
  quantecon/tests/test_lss.py
Labels: ready, refactor

#579 EHN: Add minmax solver
  docs/source/optimize.rst
  docs/source/optimize/minmax.rst
  quantecon/game_theory/normal_form_game.py
  quantecon/optimize/__init__.py
  quantecon/optimize/minmax.py
  quantecon/optimize/tests/test_minmax.py
Labels: enhancement, ready, refactor

#582 RFC: minmax: Fix redundancy
  quantecon/optimize/minmax.py
Labels: ready, refactor

#584 docs: fix a few simple typos
  docs/sphinxext/ipython_console_highlighting.py
  docs/sphinxext/ipython_directive.py
  quantecon/compute_fp.py
  quantecon/estspec.py
  quantecon/filter.py
  quantecon/game_theory/pure_nash.py
  quantecon/game_theory/tests/test_vertex_enumeration.py
  quantecon/game_theory/vertex_enumeration.py
  quantecon/lqcontrol.py
  quantecon/lss.py
  quantecon/markov/tests/test_ddp.py
  quantecon/tests/test_ivp.py
  quantecon/util/notebooks.py
Labels: ready
