Repository QuantEcon/QuantEcon.py, pull requests merged in 2022-11, with the labels that each got.

#645 CI: Fix time errors on windows and numpy warnings
  quantecon/tests/test_lqnash.py
  quantecon/util/tests/test_timing.py
Labels: tests, ready, maintenance, CI

#649 [MAINT] TST: Rename `tearDown` to `teardown_method` (pytest fixes)
  quantecon/markov/tests/test_approximation.py
  quantecon/tests/test_arma.py
  quantecon/tests/test_dle.py
  quantecon/tests/test_kalman.py
  quantecon/tests/test_lqcontrol.py
  quantecon/tests/test_lss.py
  quantecon/tests/test_rank_nullspace.py
  quantecon/tests/test_robustlq.py
  quantecon/util/tests/test_notebooks.py
Labels: tests, ready, maintenance

#650 DOCS: Remove "version" as it was deleted
  docs/qe_apidoc.py
Labels: bug, documentation

#648 MAINT: `player.is_dominated`: Allow recent methods for `scipy.optimize.linprog`
  quantecon/game_theory/normal_form_game.py
  quantecon/game_theory/tests/test_normal_form_game.py
Labels: tests, ready, maintenance

#651 FIX: Docs Issue
  docs/source/conf.py
Labels: maintenance

#653 DOC: Fix documentation warnings
  quantecon/discrete_rv.py
  quantecon/filter.py
  quantecon/game_theory/logitdyn.py
  quantecon/game_theory/support_enumeration.py
  quantecon/game_theory/vertex_enumeration.py
  quantecon/inequality.py
  quantecon/kalman.py
  quantecon/lss.py
  quantecon/optimize/nelder_mead.py
  quantecon/quadsums.py
  quantecon/util/random.py
Labels: ready, maintenance, documentation

#655 RFC: Replace `rand()` and `random_sample()` with `random()` in game_theory
  quantecon/game_theory/brd.py
  quantecon/game_theory/game_generators/bimatrix_generators.py
  quantecon/game_theory/logitdyn.py
  quantecon/game_theory/random.py
  quantecon/game_theory/tests/test_support_enumeration.py
Labels: refactor, ready

#657 FIX: Bugfix in brd.py
  quantecon/game_theory/brd.py
  quantecon/game_theory/random.py
Labels: bug, refactor, ready

#656 [Refactor]: Make random methods compatible to RandomGenerator
  quantecon/arma.py
  quantecon/graph_tools.py
  quantecon/lqcontrol.py
  quantecon/lqnash.py
  quantecon/lss.py
  quantecon/markov/core.py
  quantecon/markov/random.py
  quantecon/quad.py
  quantecon/random/utilities.py
Labels: refactor, ready

#654 ENH: check_random_state: Accept `np.random.Generator`
  docs/rtd-requirements.txt
  pyproject.toml
  quantecon/arma.py
  quantecon/discrete_rv.py
  quantecon/game_theory/brd.py
  quantecon/game_theory/game_generators/bimatrix_generators.py
  quantecon/game_theory/game_generators/tests/test_bimatrix_generators.py
  quantecon/game_theory/localint.py
  quantecon/game_theory/logitdyn.py
  quantecon/game_theory/normal_form_game.py
  quantecon/game_theory/random.py
  quantecon/game_theory/tests/test_brd.py
  quantecon/game_theory/tests/test_fictplay.py
  quantecon/game_theory/tests/test_localint.py
  quantecon/game_theory/tests/test_logitdyn.py
  quantecon/game_theory/tests/test_normal_form_game.py
  quantecon/game_theory/tests/test_random.py
  quantecon/graph_tools.py
  quantecon/lqcontrol.py
  quantecon/lqnash.py
  quantecon/lss.py
  quantecon/markov/core.py
  quantecon/markov/random.py
  quantecon/quad.py
  quantecon/random/utilities.py
  quantecon/tests/test_inequality.py
  quantecon/tests/test_quad.py
  quantecon/util/__init__.py
  quantecon/util/random.py
Labels: enhancement, refactor, ready

#661 DOC: Fix documentation warning
  quantecon/markov/ddp.py
Labels: maintenance, documentation
