Repository QuantEcon/QuantEcon.py, pull requests merged in 2022-04, with the labels that each got.

#615 MAINT: Fix pytest warnings and use pytest in Conda CI
  .github/workflows/conda_ci.yml
  .github/workflows/test.yml
  .gitignore
  environment.yml
  quantecon/dle.py
  quantecon/markov/tests/test_approximation.py
  quantecon/markov/tests/test_gth_solve.py
  quantecon/tests/test_ivp.py
  quantecon/tests/test_ricatti.py
Labels: tests, ready, CI

#621 MAINT: Remove statsmodels from dependencies
  .github/workflows/test.yml
  environment.yml
Labels: ready

#622 TEST: Exclude windows-latest python-version 3.8
  .github/workflows/conda_ci.yml
  .github/workflows/test.yml
Labels: tests, ready

#632 MAINT: Remove tests.yml and rename conda_ci.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: ready, maintenance, CI
