Repository QuantEcon/QuantEcon.py, pull requests merged in 2022-12, with the labels that each got.

#659 FIX: Fix dtype in `cartesian`
  quantecon/gridtools.py
  quantecon/tests/test_gridtools.py
Labels: bug, refactor, ready

#660 EHN: Implement `cartesian_nearest_index`
  quantecon/__init__.py
  quantecon/gridtools.py
  quantecon/tests/test_gridtools.py
Labels: enhancement, ready

#664 Unify `tauchen` and `rouwenhorst` API
  quantecon/markov/approximation.py
  quantecon/markov/tests/test_approximation.py
Labels: ready, breaking

#626 MAINT: Migrate from master to main as the default branch name
  .github/workflows/ci.yml
  quantecon/util/numba.py
  quantecon/util/tests/test_notebooks.py
Labels: maintenance

#666 FIX: Update docstring with correct reference
  quantecon/util/numba.py
Labels: ready, documentation

#667 TEST: Raise atol in test for `optimize.nelder_mead`
  quantecon/optimize/tests/test_nelder_mead.py
Labels: tests, ready

#669 Fix CHANGELOG.md
  CHANGELOG.md
Labels: maintenance

#670 MAINT: Register `cartesian_nearest_index` to __init__
  quantecon/__init__.py
Labels: ready, maintenance
