Repository QuantEcon/QuantEcon.py, pull requests merged in 2023-01, with the labels that each got.

#684 FIX: Fix period of reducible MarkovChain with custom state_values
  quantecon/markov/core.py
  quantecon/markov/tests/test_core.py
Labels: bug

#685 FIX: DOC: Remove 2-byte spaces [ci skip]
  quantecon/game_theory/localint.py
Labels: documentation

#686 FIX: Avoid bare 'except'
  quantecon/game_theory/lemke_howson.py
  quantecon/game_theory/mclennan_tourky.py
  quantecon/game_theory/support_enumeration.py
Labels: maintenance

#673 Warn only when `n` in not `int` in `tauchen`
  quantecon/markov/approximation.py
  quantecon/markov/tests/test_approximation.py
Labels: ready

#681 Add fit_discrete_mc
  quantecon/markov/__init__.py
  quantecon/markov/estimate.py
  quantecon/markov/tests/test_estimate.py
Labels: enhancement

#688 Bring estimate_mc into top level namespace
  quantecon/__init__.py
  quantecon/markov/tests/test_estimate.py
Labels: refactor, ready

#689 MAINT: Rename ivy.py to ivp.py
  quantecon/ivp.py
Labels: enhancement, ready, high priority

#690 ENH: Implement LCP solver
  docs/source/optimize.rst
  docs/source/optimize/lcp_lemke.rst
  quantecon/optimize/__init__.py
  quantecon/optimize/lcp_lemke.py
  quantecon/optimize/linprog_simplex.py
  quantecon/optimize/tests/test_lcp_lemke.py
Labels: enhancement
