Repository QuantEcon/QuantEcon.py, pull requests merged in 2023-04, with the labels that each got.

#700 RFC: Avoid bare `@jit`
  quantecon/_lss.py
Labels: refactor, ready

#701 RFC: Replace `@generated_jit` with `@overload`
  .coveragerc
  docs/rtd-requirements.txt
  pyproject.toml
  quantecon/_compute_fp.py
  quantecon/random/tests/test_utilities.py
  quantecon/random/utilities.py
  quantecon/util/numba.py
  quantecon/util/tests/test_numba.py
Labels: refactor, ready, maintenance

#696 RELEASE: Setup for v0.7.0
  CHANGELOG.md
  quantecon/__init__.py
Labels: ready
