Repository QuantEcon/QuantEcon.py, pull requests merged in 2024-08, with the labels that each got.

#733 CI: Add Python 3.12, drop 3.9
  .github/workflows/ci.yml
  environment.yml
Labels: ready, maintenance, CI

#737 CI: Remove redundant step
  .github/workflows/ci.yml
Labels: ready, CI

#738 Fixed Pandas warnings in `test_quad.py`
  quantecon/tests/test_quad.py
Labels: tests, ready, maintenance
