Repository QuantEcon/QuantEcon.py, pull requests merged in 2024-11, with the labels that each got.

#743 CI: Install libmamba from conda-forge
  .github/workflows/ci_np2.yml
Labels: ready, CI

#741 Multiplayer Polymatrix Game Solver (new for QuantEcon)
  quantecon/game_theory/__init__.py
  quantecon/game_theory/game_converters.py
  quantecon/game_theory/howson_lcp.py
  quantecon/game_theory/polymatrix_game.py
  quantecon/game_theory/random.py
  quantecon/game_theory/tests/game_files/big_polym.gam
  quantecon/game_theory/tests/game_files/huge_7_player_polymatrix.pkl
  quantecon/game_theory/tests/game_files/minimum_effort_game.gam
  quantecon/game_theory/tests/game_files/triggers_back_case.gam
  quantecon/game_theory/tests/test_howson_lcp.py
  quantecon/game_theory/tests/test_polymatrix_game.py
  quantecon/game_theory/tests/test_random.py
Labels: enhancement, ready

#744 FIX: Remove test_solves_huge_7_player_polymatrix
  quantecon/game_theory/tests/game_files/huge_7_player_polymatrix.pkl
  quantecon/game_theory/tests/test_howson_lcp.py
Labels: bug, tests, ready

#745 DOC: Update docs
  docs/source/game_theory.rst
  docs/source/game_theory/game_converters.rst
  docs/source/game_theory/howson_lcp.rst
  docs/source/game_theory/polymatrix_game.rst
  docs/source/util.rst
  docs/source/util/compat.rst
Labels: ready, documentation

#740 MAINT: docs maintenance (WIP)
  docs/make.bat
  docs/qe_apidoc.py
  docs/rtd-requirements.txt
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/index.rst
  docs/source/setup.rst
Labels: in-work

#746 CI: Install numba=0.61.0rc1, Test with Python 3.13
  .github/workflows/ci_np2.yml
  environment_np2.yml
Labels: ready, CI
