Repository QuantEcon/QuantEcon.py, pull requests merged in 2025-01, with the labels that each got.

#755 update license year
  LICENSE
Labels: ready, maintenance

#754 DOC: Add examples to `linprog_simplex`
  quantecon/optimize/linprog_simplex.py
Labels: ready, documentation

#756 MAINT: Remove unused files
  Makefile
  quantecon/bld.bat
  quantecon/build.sh
  quantecon/meta.yaml
Labels: ready, maintenance

#760 CI: Update Numba to 0.61 release version
  environment_np2.yml
Labels: ready, CI

#759 DOCS: Remove setup.py reference from docs
  docs/Makefile
  docs/README.md
Labels: maintenance

#758 RFC, ENH: Implement GAMReader and GAMWriter
  quantecon/game_theory/__init__.py
  quantecon/game_theory/game_converters.py
  quantecon/game_theory/tests/test_game_converters.py
  quantecon/game_theory/tests/test_howson_lcp.py
  quantecon/game_theory/tests/test_polymatrix_game.py
Labels: enhancement, refactor
