Repository QuantEcon/QuantEcon.py, pull requests merged in 2025-07, with the labels that each got.

#769 FIX: lcp_lemke: Fix bug in first iteration
  quantecon/optimize/lcp_lemke.py
  quantecon/optimize/tests/test_lcp_lemke.py
Labels: bug, ready

#772 FIX: Update `solve_discrete_riccati`
  quantecon/_matrix_eqn.py
Labels: bug, ready

#770 Fix: Readme to have stable vs latest py badges
  README.md
Labels: ready, maintenance

#774 MAINT: Update README.md
  README.md
Labels: ready, maintenance

#775 CI: Add Python 3.13, drop 3.10
  .github/workflows/ci.yml
Labels: ready, maintenance, CI

#778 DOC, FIX: Correct docstring for `linprog_simplex`
  quantecon/optimize/linprog_simplex.py
Labels: ready, documentation

#780 DOC: Fix copyright year
  docs/source/conf.py
Labels: ready, maintenance, documentation
